export const AJAX_START = "AJAX_START";
export const AJAX_COMPLETE = "AJAX_COMPLETE";
export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const ADD_PRICE = "ADD_PRICE";
export const REMOVE_PRICE = "REMOVE_PRICE";
export const FETCH_INGREDIENTS_ACTIONS_SUCCESS =
  "FETCH_INGREDIENTS_ACTIONS_SUCCESS";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
//export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCHING_ORDER = "FETCHING_ORDER";
export const FETCHING_INGREDIENTS = "FETCHING_INGREDIENTS";
